# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Pandoc Document Converter
        # You may pin to the exact commit or the version.
        # uses: maxheld83/pandoc-action@65a2c5927b84724fe0febcff7db28605d10302d5
        uses: maxheld83/pandoc-action@v2
      - name: TeXLive Action
        # You may pin to the exact commit or the version.
        # uses: fredqi/tl-action@6713a805bd9bab56c4777f06c62b10de1c787750
        uses: fredqi/tl-action@mini-v2
      - name: Run a multi-line script
        run: |
          tar -czvf release.tar .
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: release.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
